"""changed comment realtionship

Revision ID: 1d86ab3035f4
Revises: d794077ecfea
Create Date: 2021-11-29 18:53:37.579615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d86ab3035f4'
down_revision = 'd794077ecfea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
